steps:
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.4.4'
    dir:  './infra'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
      echo "Applying TF"
      pwd
      # terraform init
      # terraform plan