steps:
  - id: "keyring"
    name: python
    entrypoint: pip
    args: ["install", "keyring"]
  - id: "keyring"
    name: python
    entrypoint: pip
    args: ["install", "keyrings.google-artifactregistry-auth"]
  - id: "tf apply"
    name: "hashicorp/terraform:1.4.4"
    dir: "./slsainfra"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Applying TF"
        terraform init
        terraform apply --auto-approve
