steps:
  - id: "pybuild"
    name: python
    entrypoint: pip
    args: ["install", "keyring"]

  - id: "tf apply"
    name: "hashicorp/terraform:1.4.4"
    dir: "./slsainfra"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Applying TF"
        terraform init
        terraform apply --auto-approve
