steps:
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.4.4'
    dir:  './slsainfra'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      echo "Applying TF"
      pwd
      ls -l
      uname -a
      # terraform init
      # terraform plan
