steps:
  - id: "install-keyring"
    waitFor: ['-']
    name: python
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Keyring"
        pip install keyring
        pip install keyrings.google-artifactregistry-auth
        keyring --list-backends


  - id: "tf-apply"
    waitFor: ['install-keyring']
    name: "hashicorp/terraform:1.4.4"
    dir: "./slsainfra"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Applying TF"
        terraform init
        terraform apply --auto-approve
